export const makeOptions: Array<{
  category: string;
  options: Record<string, string>;
}> = [
  {
    category: "Popular makes",
    options: {
      acura: "Acura",
      audi: "Audi",
      bmw: "BMW",
      buick: "Buick",
      cadillac: "Cadillac",
      chevrolet: "Chevrolet",
      chrysler: "Chrysler",
      dodge: "Dodge",
      ford: "Ford",
      gmc: "GMC",
      honda: "Honda",
      hyundai: "Hyundai",
      infiniti: "Infiniti",
      jaguar: "Jaguar",
      jeep: "Jeep",
      kia: "Kia",
      land_rover: "Land Rover",
      lexus: "Lexus",
      lincoln: "Lincoln",
      mazda: "Mazda",
      mercedes_benz: "Mercedes-Benz",
      mitsubishi: "Mitsubishi",
      nissan: "Nissan",
      porsche: "Porsche",
      ram: "RAM",
      subaru: "Subaru",
      tesla: "Tesla",
      toyota: "Toyota",
      volkswagen: "Volkswagen",
      volvo: "Volvo",
    },
  },
  {
    category: "Other makes",
    options: {
      ac: "AC",
      alfa_romeo: "Alfa Romeo",
      am_general: "Am General",
      american_motors: "American Motors",
      aston_martin: "Aston Martin",
      austin_healey: "Austin-Healey",
      bentley: "Bentley",
      bugatti: "Bugatti",
      datsun: "Datsun",
      detomaso: "DeTomaso",
      delorean: "Delorean",
      eagle: "Eagle",
      fiat: "FIAT",
      ferrari: "Ferrari",
      fisker: "Fisker",
      genesis: "Genesis",
      geo: "Geo",
      hudson: "Hudson",
      hummer: "Hummer",
      international: "International",
      isuzu: "Isuzu",
      jensen: "Jensen",
      kaiser: "Kaiser",
      karma: "Karma",
      koenigsegg: "Koenigsegg",
      lamborghini: "Lamborghini",
      lotus: "Lotus",
      mg: "MG",
      mini: "MINI",
      maserati: "Maserati",
      maybach: "Maybach",
      mclaren: "McLaren",
      mercury: "Mercury",
      nash: "Nash",
      oldsmobile: "Oldsmobile",
      opel: "Opel",
      packard: "Packard",
      pagani: "Pagani",
      panoz: "Panoz",
      plymouth: "Plymouth",
      polestar: "Polestar",
      pontiac: "Pontiac",
      rolls_royce: "Rolls-Royce",
      saab: "Saab",
      saturn: "Saturn",
      scion: "Scion",
      studebaker: "Studebaker",
      sunbeam: "Sunbeam",
      suzuki: "Suzuki",
      triumph: "Triumph",
      willys: "Willys",
      smart: "Smart",
    },
  },
];

export const modelOptions = {};

export const yearOptions: Record<string | number, string> = {
  2021: "2021",
  2020: "2020",
  2019: "2019",
};

export const priceOptions = {
  2000: "$2,000",
  4000: "$4,000",
  6000: "$6,000",
  8000: "$8,000",
  10000: "$10,000",
  15000: "$15,000",
  20000: "$20,000",
  25000: "$25,000",
  30000: "$30,000",
  35000: "$35,000",
  40000: "$4,000",
  45000: "$45,000",
  50000: "$50,000",
  60000: "$60,000",
  70000: "$70,000",
  80000: "$80,000",
  90000: "$90,000",
  100000: "$10,000",
  125000: "$125,000",
  150000: "$150,000",
  175000: "$175,000",
};
